active_personality_id: 15
audio_auto_send_input: true
audio_in_language: en-US
audio_out_voice: Google UK English Female
audio_pitch: '1'
audio_silenceTimer: 5000
auto_save: true
auto_show_browser: true
auto_speak: false
auto_update: true

binding_name: null
model_name: null

config: local_config
ctx_size: 4090
data_vectorization_activate: true
data_vectorization_build_keys_words: true
data_vectorization_chunk_size: 512
data_vectorization_method: tfidf_vectorizer
data_vectorization_nb_chunks: 3
data_vectorization_overlap_size: 128
data_vectorization_save_db: false
data_visualization_method: PCA
db_path: lollms.db
debug: true
discussion_prompt_separator: '!@>'
enable_gpu: true
extensions: []
host: localhost
min_n_predict: 256
n_predict: 1024
n_threads: 8
override_personality_model_parameters: false
personalities:
- generic/lollms
port: 9600
repeat_last_n: 40
repeat_penalty: 1.2
seed: -1
temperature: '0.3'
top_k: 50
top_p: 0.95
use_discussions_history: true
use_files: true
use_user_informations_in_discussion: false
use_user_name_in_discussions: true
user_avatar: default_user
user_description: 
user_name: User
version: 26
